[package]
name = "omni_setup"
rust-version.workspace = true
edition.workspace = true
version = "0.0.0"
authors.workspace = true
repository.workspace = true

[features]
default = ["enable-tracing"]
enable-tracing = ["dep:tracing", "trace/enabled"]

[dependencies]
eyre = { workspace = true }
thiserror = { workspace = true }
strum = { workspace = true }
trace = { workspace = true }
tracing = { workspace = true, optional = true }
serde = { workspace = true }
omni_configurations = { workspace = true }
omni_remote_cache_client = { workspace = true }
derive_builder = { workspace = true }
derive-new = { workspace = true }
keyring = { workspace = true }
machine-uid = { workspace = true }
rand = { workspace = true }
ring = { workspace = true }
base64 = { workspace = true }
rmp-serde = { workspace = true }
tokio = { workspace = true }
omni_file_data_serde = { workspace = true }
system_traits = { workspace = true, features = ["memory-async", "memory-sync", "real-sync", "real-async-tokio"] }
