[package]
name = "system_traits"
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
version = "0.1.0"

[features]
default = ["sync", "async"]
sync = ["dep:sys_traits"]
async = ["dep:async-trait"]
real-async-tokio = ["dep:tokio", "async", "dep:sys_traits", "sys_traits/real"]
memory-async = ["async", "dep:sys_traits", "sys_traits/memory"]
real-sync = ["dep:sys_traits", "sys_traits/real", "sync"]
memory-sync = ["dep:sys_traits", "sys_traits/memory", "sync"]

[dependencies]
tokio = { workspace = true, optional = true }
sys_traits = { workspace = true, optional = true, features = [] }
async-trait = { workspace = true, optional = true }
