[github]
owner = "omni-oss"
repo = "omni"

[bot.releases]
enabled = true
pull_request.title = "Release $version"

[bot.checks]
enabled = true

[packages.omni]
versioned_files = ["./cli/omni/Cargo.toml"]
changelog = "./cli/omni/.changelog/CHANGELOG.md"

[packages.omni_remote_cache_service]
versioned_files = ["./services/omni_remote_cache_service/Cargo.toml"]
changelog = "./services/omni_remote_cache_service/.changelog/CHANGELOG.md"

[packages."@omni-oss/async-utils"]
versioned_files = ["./packages/async-utils/package.json"]
changelog = "./packages/async-utils/.changelog/CHANGELOG.md"

[packages."@omni-oss/biome-config"]
versioned_files = ["./packages/biome-config/package.json"]
changelog = "./packages/biome-config/.changelog/CHANGELOG.md"

[packages."@omni-oss/bridge-rpc"]
versioned_files = ["./packages/bridge-rpc/package.json"]
changelog = "./packages/bridge-rpc/.changelog/CHANGELOG.md"

[packages."@omni-oss/bridge-rpc-router"]
versioned_files = ["./packages/bridge-rpc-router/package.json"]
changelog = "./packages/bridge-rpc-router/.changelog/CHANGELOG.md"

[packages."@omni-oss/channels"]
versioned_files = ["./packages/channels/package.json"]
changelog = "./packages/channels/.changelog/CHANGELOG.md"

[packages."@omni-oss/system-interface"]
versioned_files = ["./packages/system-interface/package.json"]
changelog = "./packages/system-interface/.changelog/CHANGELOG.md"

[packages."@omni-oss/tsconfig"]
versioned_files = ["./packages/tsconfig/package.json"]
changelog = "./packages/tsconfig/.changelog/CHANGELOG.md"

[packages."@omni-oss/vite-config"]
versioned_files = ["./packages/vite-config/package.json"]
changelog = "./packages/vite-config/.changelog/CHANGELOG.md"

[packages."@omni-oss/vitest-config"]
versioned_files = ["./packages/vitest-config/package.json"]
changelog = "./packages/vitest-config/.changelog/CHANGELOG.md"
