[package]
name = "omni_tera"
rust-version.workspace = true
edition.workspace = true
version = "0.4.0"
authors.workspace = true
repository.workspace = true

[lib]
name = "omni_tera"
path = "src/lib.rs"
[features]
default = ["enable-tracing"]
enable-tracing = ["dep:tracing", "trace/enabled"]

[dependencies]
eyre = { workspace = true }
thiserror = { workspace = true }
strum = { workspace = true }
trace = { workspace = true }
tracing = { workspace = true, optional = true }
derive_builder = { workspace = true }
derive-new = { workspace = true }
tera = { workspace = true }
heck = { workspace = true }
cruet = { workspace = true }
pathdiff = { workspace = true }
