[package]
name = "omni_hasher"
rust-version.workspace = true
edition.workspace = true
version = "0.1.0"
repository.workspace = true

[features]
default = ["blake3", "enable-tracing"]
enable-tracing = ["trace/enabled"]
blake3 = ["dep:blake3"]

[dependencies]
eyre = { workspace = true }
thiserror = { workspace = true }
strum = { workspace = true }
system_traits = { workspace = true }
blake3 = { workspace = true, optional = true }
serde = { workspace = true }
async-trait = { workspace = true }
rs_merkle = { workspace = true }
omni_types = { workspace = true }
derive-new = { workspace = true }
derive_builder = { workspace = true }
futures = { workspace = true }
byteorder = { workspace = true }
dir_walker = { workspace = true }
bincode = { workspace = true }
omni_utils = { workspace = true }
trace = { workspace = true, optional = true }
tracing = { workspace = true, optional = true }
path-clean = { workspace = true }


[dev-dependencies]
tempfile = { workspace = true }
tokio = { workspace = true }
