[package]
name = "omni_test_utils"
rust-version.workspace = true
edition.workspace = true
version = "0.0.0"
authors.workspace = true
repository.workspace = true

[features]
default = ["enable-tracing"]
enable-tracing = ["dep:tracing"]

[dependencies]
eyre = { workspace = true }
thiserror = { workspace = true }
strum = { workspace = true }
trace = { workspace = true, optional = true }
tracing = { workspace = true, optional = true }
serde = { workspace = true }
serde_norway = { workspace = true }
omni_types = { workspace = true }
omni_configurations = { workspace = true }
#tempfile = { workspace = true }
derive_builder = { workspace = true }
config_utils = { workspace = true, features = [
    "serde",
    "schemars",
    "validator-garde",
] }
bs58 = { workspace = true }
