[package]
name = "omni_generator"
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true

[lib]
path = "src/lib.rs"

# [[bench]]
# path = "./benches/omni_generator_benchmarks.rs"
# name = "omni_generator_benchmarks"
# harness = false

[features]
default = ["enable-tracing"]
enable-tracing = ["trace/enabled", "dep:tracing"]

[dependencies]
thiserror = { workspace = true }
eyre = { workspace = true }
strum = { workspace = true }
trace = { workspace = true }
tracing = { workspace = true, optional = true }
tera = { workspace = true }
derive-new = { workspace = true }
omni_generator_configurations = { workspace = true }
omni_prompt = { workspace = true }
omni_discovery = { workspace = true }
system_traits = { workspace = true, features = [
    "real-sync",
    "real-async-tokio",
    "memory-sync",
    "memory-async"
] }
requestty = { workspace = true }
value-bag = { workspace = true }
maps = { workspace = true }
sets = { workspace = true }
dir_walker = { workspace = true }
omni_configuration_discovery = { workspace = true }
omni_file_data_serde = { workspace = true }
tokio = { workspace = true }
path-clean = { workspace = true }
async-trait = { workspace = true }
either = { workspace = true }
serde_json = { workspace = true }
omni_tera = { workspace = true }
enum-map = { workspace = true }
omni_types = { workspace = true }
regex = { workspace = true }
omni_process = { workspace = true }
omni_utils = { workspace = true }
env = { workspace = true }
which = { workspace = true }
pathdiff = { workspace = true }
