[package]
name = "omni_generator"
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true

[lib]
path = "src/lib.rs"

# [[bench]]
# path = "./benches/omni_generator_benchmarks.rs"
# name = "omni_generator_benchmarks"
# harness = false

[features]
default = ["enable-tracing"]
enable-tracing = ["trace/enabled", "dep:tracing"]

[dependencies]
thiserror = { workspace = true }
eyre = { workspace = true }
strum = { workspace = true }
trace = { workspace = true }
tracing = { workspace = true, optional = true }
tera = { workspace = true }
derive-new = { workspace = true }
omni_generator_configurations = { workspace = true }
omni_prompt = { workspace = true }
system_traits = { workspace = true }
requestty = { workspace = true }
value-bag = { workspace = true }
maps = { workspace = true }
sets = { workspace = true }
dir_walker = { workspace = true }
omni_configuration_discovery = { workspace = true }
omni_file_data_serde = { workspace = true }
tokio = { workspace = true }
