[package]
name = "omni_process"
rust-version.workspace = true
edition.workspace = true
version = "0.2.0"
repository.workspace = true

[features]
default = ["enable-tracing"]
enable-tracing = ["trace/enabled"]

[dependencies]
eyre = { workspace = true }
thiserror = { workspace = true }
strum = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
omni_core = { workspace = true }
portable-pty = { workspace = true }
terminal_size = { workspace = true }
atty = { workspace = true }
trace = { workspace = true }
tracing = { workspace = true }
shlex = { workspace = true }
omni_hasher = { workspace = true }
system_traits = { workspace = true }
bytes = { workspace = true }
derive-new = { workspace = true }
futures = { workspace = true }
maps = { workspace = true }
env = { workspace = true }
nix = { workspace = true, features = ["process", "term"] }
