[package]
name = "omni_task_context"
rust-version.workspace = true
edition.workspace = true
version = "0.1.0"
repository.workspace = true

[features]
default = ["enable-tracing"]
enable-tracing = ["trace/enabled"]

[dependencies]
eyre = { workspace = true }
thiserror = { workspace = true }
strum = { workspace = true }
serde = { workspace = true }
derive-new = { workspace = true }
derive_builder = { workspace = true }
globset = { workspace = true }
trace = { workspace = true }
tracing = { workspace = true }
maps = { workspace = true }
omni_core = { workspace = true }
omni_types = { workspace = true }
omni_hasher = { workspace = true }
omni_tera = { workspace = true }
