[package]
name = "trace"
rust-version.workspace = true
edition.workspace = true
version = "0.1.0"
repository.workspace = true

[features]
default = ["enabled"]
enabled = ["dep:tracing"]


[dependencies]
tracing = { workspace = true, optional = true }
