[package]
name = "omni_file_data_serde"
rust-version.workspace = true
edition.workspace = true
version = "0.0.0"
authors.workspace = true
repository.workspace = true

[features]
default = ["enable-tracing"]
enable-tracing = ["dep:tracing", "trace/enabled"]

[dependencies]
eyre = { workspace = true }
thiserror = { workspace = true }
strum = { workspace = true }
trace = { workspace = true }
tracing = { workspace = true, optional = true }
serde = { workspace = true }
serde_norway = { workspace = true }
toml = { workspace = true }
serde_json = { workspace = true }
rmp-serde = { workspace = true }
system_traits = { workspace = true, features = ["memory-sync", "memory-async"] }

[dev-dependencies]
tokio = { workspace = true }
