[package]
name = "omni_prompt"
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
version = "0.2.1"

[lib]
path = "src/lib.rs"

# [[bench]]
# path = "./benches/omni_generator_benchmarks.rs"
# name = "omni_generator_benchmarks"
# harness = false

[features]
default = ["enable-tracing"]
enable-tracing = ["trace/enabled", "dep:tracing"]

[dependencies]
thiserror = { workspace = true }
eyre = { workspace = true }
strum = { workspace = true }
trace = { workspace = true }
tracing = { workspace = true, optional = true }
derive-new = { workspace = true }
tera = { workspace = true }
system_traits = { workspace = true }
requestty = { workspace = true }
value-bag = { workspace = true }
maps = { workspace = true }
sets = { workspace = true }
serde = { workspace = true }
schemars = { workspace = true }
garde = { workspace = true }
serde_validate = { workspace = true }
omni_serde_validators = { workspace = true }
either = { workspace = true }
serde_json = { workspace = true }
omni_tera = { workspace = true }
