[package]
name = "omni_path_utils"
rust-version.workspace = true
edition.workspace = true
version = "0.1.0"
authors.workspace = true
repository.workspace = true

[features]
default = ["enable-tracing"]
enable-tracing = ["dep:tracing"]

[dependencies]
eyre = { workspace = true }
thiserror = { workspace = true }
strum = { workspace = true }
trace = { workspace = true, optional = true }
tracing = { workspace = true, optional = true }
