name: Check PR Message

on:
  push:
    tags-ignore:
      - "v*.*.*"
      - "*-v*.*.*"

jobs:
  cog_check_job:
    runs-on: ubuntu-latest
    name: Check Conventional Commit Compliance
    steps:
      - uses: actions/checkout@main
        with:
          fetch-depth: 0

      - name: Conventional Commits Check
        uses: cocogitto/cocogitto-action@v3
