[package]
name = "omni_scm"
rust-version.workspace = true
edition.workspace = true
version.workspace = true
authors.workspace = true
repository.workspace = true

[features]
default = ["enable-tracing"]
enable-tracing = ["dep:tracing", "trace/enabled"]
vendored-openssl = ["git2/vendored-openssl"]

[dependencies]
eyre = { workspace = true }
thiserror = { workspace = true }
strum = { workspace = true }
trace = { workspace = true }
tracing = { workspace = true, optional = true }
serde = { workspace = true }
derive_builder = { workspace = true }
derive-new = { workspace = true }
tokio = { workspace = true }
git2 = { workspace = true }
